In [9]:
import numpy as np


#Generates N nodes and returns an array of tuples of their position.
def N_node_gen(N):
    node_list = list()
    for _ in range(N):
        node_list.append(np.array((np.random.random(), np.random.random())))
    return node_list

test_nodes = N_node_gen(5)
test_nodes

[array([0.05400742, 0.63444603]),
 array([0.12860957, 0.06762378]),
 array([0.35429638, 0.26400617]),
 array([0.45346923, 0.52606854]),
 array([0.88496425, 0.28261421])]

In [11]:
import numpy as np

#Returns adjacency matrix of the generated graph

def adj_mat_gen(node_list, R):
    N = len(node_list)
    adj_mat = np.zeros((N, N))
    for i in range(N):
        for j in range(i+1, N):
            dist = np.linalg.norm(node_list[i]-node_list[j])
            if dist < R:
                adj_mat[i, j] = 1 - dist/R
                adj_mat[j, i] = 1 - dist/R
    return adj_mat

test_adj_mat = adj_mat_gen(test_nodes, 0.5)

test_adj_mat

array([[0.        , 0.        , 0.04627228, 0.17219468, 0.        ],
       [0.        , 0.        , 0.40166704, 0.        , 0.        ],
       [0.04627228, 0.40166704, 0.        , 0.43960038, 0.        ],
       [0.17219468, 0.        , 0.43960038, 0.        , 0.00912571],
       [0.        , 0.        , 0.        , 0.00912571, 0.        ]])