In [7]:
import numpy as np


#Generates N nodes and returns an array of tuples of their position.
def N_node_gen(N):
    node_list = list()
    for _ in range(N):
        node_list.append(np.array((np.random.random(), np.random.random())))
    return node_list

N_node_gen(5)

[array([0.13317475, 0.22848038]),
 array([0.85794903, 0.90405901]),
 array([0.21114121, 0.33611569]),
 array([0.56088865, 0.36564156]),
 array([0.10742852, 0.23761792])]