In [9]:
import numpy as np


#Generates N nodes and returns an array of tuples of their position.
def N_node_gen(N):
    node_list = list()
    for _ in range(N):
        node_list.append(np.array((np.random.random(), np.random.random())))
    return node_list

test_nodes = N_node_gen(5)
test_nodes

[array([0.05400742, 0.63444603]),
 array([0.12860957, 0.06762378]),
 array([0.35429638, 0.26400617]),
 array([0.45346923, 0.52606854]),
 array([0.88496425, 0.28261421])]

In [26]:
import numpy as np

#Returns adjacency matrix of the generated graph

def adj_mat_gen(node_list, R):
    N = len(node_list)
    adj_mat = np.zeros((N, N), dtype=np.float64)
    for i in range(N):
        for j in range(i+1, N):
            dist = np.linalg.norm(node_list[i]-node_list[j])
            if dist < R:
                adj_mat[i, j] = 1 - dist/R
                adj_mat[j, i] = 1 - dist/R
    return adj_mat

test_adj_mat = adj_mat_gen(test_nodes, 0.5)

test_adj_mat

array([[0.        , 0.        , 0.04627228, 0.17219468, 0.        ],
       [0.        , 0.        , 0.40166704, 0.        , 0.        ],
       [0.04627228, 0.40166704, 0.        , 0.43960038, 0.        ],
       [0.17219468, 0.        , 0.43960038, 0.        , 0.00912571],
       [0.        , 0.        , 0.        , 0.00912571, 0.        ]])

In [29]:
#Produces the matrix W(i)

def W_i_gen(i, adj_mat, gamma):
    i -= 1
    W_i = np.zeros(np.shape(adj_mat), dtype=np.float64)
    N = np.shape(adj_mat)[0]
    for j in range(N):
        if adj_mat[i, j]:
            val = adj_mat[i, j].item()
            W_i[j, j] = gamma * val
            W_i[j, i] = 1 - gamma * val
        else:
            W_i[j, j] = 1
    return W_i

test_W_1 = W_i_gen(1, test_adj_mat, 0.5)

test_W_1

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.97686386, 0.        , 0.02313614, 0.        , 0.        ],
       [0.91390266, 0.        , 0.        , 0.08609734, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

In [30]:
#A single step of the simulation

def update_step(x, adj_mat, gamma):
    N = len(x)
    i = np.random.randint(N, size=1)
    W_i = W_i_gen(i, adj_mat, gamma)
    return np.matmul(W_i, x)

test_x = np.random.random(size=5)
update_step(test_x, test_adj_mat, 0.5)

array([0.61735218, 0.51062788, 0.74681145, 0.10324995, 0.102715  ])